name: FactionsKeyDrop
version: 1.0
description: Mob droppano frammenti di Key
author: claxon007
main: it.evermine.factionskeydrop.FactionsKeyDrop

commands:
  givekey:
    usage: /<command>
  convertkey:
    usage: /<command>